// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSNEcitludekWOToChP9i1V-floY8jQwI',
    appId: '1:1082380050255:web:ce831ab0420e1cc2eb6f3a',
    messagingSenderId: '1082380050255',
    projectId: 'biblia-app-56931',
    authDomain: 'biblia-app-56931.firebaseapp.com',
    databaseURL: 'https://biblia-app-56931-default-rtdb.firebaseio.com',
    storageBucket: 'biblia-app-56931.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTWBamlDrw7jAdMjUPfmgCtcMRv7dCyeg',
    appId: '1:1082380050255:android:17ce7c5c485c2100eb6f3a',
    messagingSenderId: '1082380050255',
    projectId: 'biblia-app-56931',
    databaseURL: 'https://biblia-app-56931-default-rtdb.firebaseio.com',
    storageBucket: 'biblia-app-56931.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqlMvUXTfnxHKLrkc-dmOATbe3GAFcHLw',
    appId: '1:1082380050255:ios:934a6c85b263e878eb6f3a',
    messagingSenderId: '1082380050255',
    projectId: 'biblia-app-56931',
    databaseURL: 'https://biblia-app-56931-default-rtdb.firebaseio.com',
    storageBucket: 'biblia-app-56931.appspot.com',
    iosBundleId: 'com.example.bibliaApp',
  );

}