texto_inicial = """

Hoy, yom 8 del 5º Mes del año 6000 del Calendario dado a Yisrael a través del Profeta Yanokj, vino a mí, Palabra de Yahweh para que escribiera sin tardanza como de una prontitud inmediata por lo corto ya del Tiempo y me dijo “Escribe Mis Palabras para ellos”
Así dice Yahweh, Tu Redentor:
¿Quién se ha levantado en este Tiempo del Fin para anunciar Mi Misericordia? ¿No es acaso mi siervo a quien yo llame por mi propia Voluntad? ¿Quién se levantó para cerrar la brecha que mi Pueblo Yisrael abrió por causa de sus pecados e infidelidades en toda su historia?
¿Quién de los que llamaste se levantó para Escucharme y Obedecerme?
¿Quién fue al que regalé Mi Misericordia a brazos abiertos? ¿De quién me compadecí para traer de vuelta a Mi Pueblo a Mi Redil? ¿A quién le revelé Mi Plan y puse en sus manos lo que haría al comienzo de la Restauración y que aún estaba oculto a Mi Pueblo?
¿No fue a mi siervo, menospreciado, difamado por muchos y traicionado por los que él confiaba?
Y le dije:
“Solo Tu lo sabes, Oh Excelso Elohe, Amado Abba, el Compasivo, el Benévolo, el Misericordioso”
Él respondió:
“Tú y los que Me Escucharon a través de ti y de Obedecer las Directrices de Mi Hijo Amado Yahshua que ha permanecido Fiel y siempre a vuestro lado y que nunca habéis negado que él está con vosotros hasta el fin, es a vosotros y al resto de la Descendencia de ustedes que mando leer esta carta”
“Ustedes, Mis hijos de Filadelfia ya marcháis camino al Desierto, porque vuestras obras de obediencia os preceden, como os preceden vuestra Obediencia a Mí y en breve ya seréis trasladados allí para continuar con vuestra Comisión como Kohanim, Reyes y Jueces junto a Mi Hijo Yahshua”
“No teman mis Primicias, el enemigo os quiere destruir y si así se le permitiera lo haría, pero confíen, Mi Promesa ya la puse en los labios y las Manos de Mi Hijo para que os protegiera en la prueba Final que acontecerá a todos en este Fin inmediato”
“Pero no podré proteger al resto de la Descendencia, porque los elegí para ser el Testimonio de Fe Final y deben lavar sus ropas en la sangre del Cordero dando su propia vida como sacrificio de Testimonio a las naciones, pero de forma inmediata al Regreso del Juez Nombrado, Mi Hijo, él los resucitará y junto a Filadelfia, la Protegida Primicia en el Desierto, serán recogidos para encontrarse con Él y establecer desde Sión, Mi Maljut, Mi Gobierno Justo y Eterno dirigido por Mi propio Hijo Nombrado desde antes de la fundación del mundo”
Así hare, mi Elohe, y también le compartiré lo que Tú me has permitido restaurar, Tu Escritura Verdadera que fue contaminada, adulterada y cambiada por la mano de los escribas mentirosos para que Laodicea pueda Glorificar Tu Poder y pueda tener entre sus manos, la hermosa restauración de la Doctrina verdadera que había sido ocultada entre las líneas de Tu Davar porque aún no había llegado el Tiempo de revelarla a Tu Pueblo.
Estimados ajaim, hermanos en la Emuná de Yahweh y de su Hijo Amado Yahshua, la Salvación de Yahweh, es a vosotros a quien me dirijo humildemente para anunciaros La Buena Nueva de vuestra Restauración en las Manos de Yahshua, Autor y consumador de la FE.
Sabed YA, que los primeros ya marchamos, Filadelfia, y de todos a los que Yahweh llamó, solo un pequeño remanente Le Escuchó y quiso estar en esa brecha, defendiendo la Causa de Su Hijo Yahshua, causa que llevará a muchos de ustedes, la mitad de la totalidad de los que vais a ser llamados, a tomar ejemplos de vida, de FE, de Lealtad, de coraje y que harán en este Tiempo del Fin que Su Mensaje se extienda de un extremo a otro extremo del mundo para que se culmine Tu Salvación.
Hombres y mujeres valientes a los cuales les darás de Tu Aliento para permanecer fieles, Resto final de Tu Rebaño Yisrael para poder así completarse la Promesa de Yahshua de que había venido solo a “buscar las ovejas perdidas de Yisrael, las Dos Casas y así con Su Mano unir esas Dos casas EN UNA SOLA, Yahudah y Efraím.
Hombres y mujeres valientes, persistentes, que vais a enfrentaros a la Gran Tribulación y la lucha de querer siempre hacer lo que es bueno a los Ojos de Vuestro Comandante.
Hombres y mujeres que aún con todo el mundo a vuestra contra, como así Yahshua lo profetizó, estaréis dispuestos a darlo todo por seguir confiando en la Promesa del Regreso de Aquel que nos amó a todos.
Hombres y mujeres, que junto a los que seremos llevados al Desierto, seréis también reponedores de caminos como el Profeta YeshaYah        profetizó para que podáis seguir edificando hasta el final, las ruinas antiguas, y poniendo lo que quedará por poner de los cimientos en el Pueblo de Yisrael y a los cuales el Profeta también a vosotros os llamó. Vosotros continuareis la obra por un corto periodo de tiempo de reparar los Portillos, y restaurar las calzadas para que vosotros podáis caminar en su Tiempo Final de Gran Tribulación.
Para eso Yahshua ahora os llama, para daros el Ruaj, Su Ruaj, y así tener la autoridad que necesitáis para demostrar quién es vuestro Adon de Shalom. Ustedes dejareis vuestro Legado final a un mundo soberbio, alejado de Yahweh y culpable de haber arruinado la Tierra y destruido los corazones de los seres humanos y amados míos, soy yo, Yhemaelh Zeev, siervo pequeño quien os escribo esta carta siendo ella, primicia de vuestro llamamiento a las filas del Ejercito Leal que se prepara para recibir al Rey de Reyes anunciado por todos los Profetas, ustedes, los que lean esta carta, seréis los primeros en recibir la apertura de vuestro comienzo final”.
Es a vosotros, resto de la Descendencia de Yisrael a quienes se os ha dado la Comisión del Gran Maestro para que llevéis su Mensaje Final a todas las naciones, Mensaje de arrepentimiento y de Juicio.
Es a vosotros, Laodicea, que se os Comisiona por el Gran Maestro a predicar en este Tiempo del Fin, poniendo vuestra mira siempre “en la higuera Yisrael” en la Tierra donde Regresará y pisará y establecerá EL REINO MILENIAL, nuestro Kohen Gadol y Rey, Yahshua Shiló (el que regresa).
Os dejamos el trabajo que realizamos y que se encuentra en el Blog de Estudios de la Kajal Yisraelí de Yahshua Shiló, también en nuestra Página Web “caminoayahweh” en donde os podréis alimentar ahora y después de que nos vayamos, trabajo de Restauración de la Escritura y de la Sana Doctrina que fue pervertida por las religiones que fueron las culpables de cambiar la Verdad por la mentira.
Salid del cristianismo y del mesianismo y aprended y paraos “en las sendas Antiguas” donde la Verdad no fue tocada por mano perversa.
No sé cuanto tiempo debemos aún estar aquí la Kajal de Filadelfia, Real Sacerdocio de Mal-TKisedet, pero sabemos, que, a su debido tiempo, seremos trasladados, sacados de la escena del mundo, pero quiero que sepáis, que os amamos y que todo lo que hicimos, por amor a vosotros lo hicimos en Obediencia a las Directrices de Yahshua para nosotros.
Cuando ya no nos veamos, no os preocupéis, en breve nos veremos todos juntos, y sé, que, vuestra Gran Tribulación, será breve, porque Yahweh en Su Misericordia, “acortará esos días” para que ninguno de ustedes se pierda por el grandísimo sufrimiento de vuestras vidas.
Que la Shalom, la Fe, la perseverancia os acompañe amados hermanos.
"""